# Generated by Django 4.2.23 on 2025-07-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('TopWear', 'Top Wear'), ('BottomWear', 'Bottom Wear'), ('WinterWear', 'Winter Wear'), ('Combo', 'Outfits')], max_length=15),
        ),
    ]
