# Generated by Django 4.2.23 on 2025-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='S', max_length=3),
            preserve_default=False,
        ),
    ]
